version: '0.5.4.dev.{build}'

environment:
  global:
    # Example can be found here https://github.com/quantopian/zipline/blob/master/appveyor.yml
    PYTHON_LOC: "C:\\Miniconda35-x64"
    INSTALLER_VERSION: "0.5.4.dev"

install:
  - cmd: call %PYTHON_LOC%\Scripts\activate.bat
  - cmd: conda config --set always_yes yes --set changeps1 no
  - cmd: conda install -y constructor

build_script:
  - cmd: constructor installer

deploy:
  - provider: FTP
    protocol: ftp
    host: ftp.brockmann-consult.de
    username: dedop
    password:
      secure: GL7E4cOZi9mzFvaDMAVOaQ==
    artifact: /DeDop.*\.exe/
    folder: win64
    debug: true