version: '0.0.1.dev.{build}'

environment:
  global:
    PYTHON_LOC: "C:\\Miniconda35-x64"
    FRONTEND_VERSION: "0.0.1.dev"
  nodejs_version: "6.9.0"
  apiUrl : "https://ci.appveyor.com/api"

cache:
  - dedop-installer\node_modules -> package.json

install:
  - cmd: call %PYTHON_LOC%\Scripts\activate.bat
  - cmd: conda config --set always_yes yes --set changeps1 no
  - cmd: conda install -y constructor
  # now the frontend build
  - cmd: git clone https://github.com/DeDop/dedop-studio.git
  - cmd: cd dedop-studio
  - ps: $apiUrl
  - ps: Install-Product node $env:nodejs_version
  - cmd: npm install npm
  - cmd: .\node_modules\.bin\npm install
  - cd ..

build_script:
  - cmd: constructor installer
  - ps: $CONDA_INSTALLER_FILE="DeDop*.exe"
  - cmd: mkdir dedop-studio\app\backend-installer
  - ps: cp $CONDA_INSTALLER_FILE dedop-studio\app\backend-installer
  - cmd: cd dedop-studio
  - cmd: .\node_modules\.bin\npm run dist
  - ps: ls $APPVEYOR_BUILD_FOLDER
  - ps: echo $APPVEYOR_BUILD_FOLDER
  - ps: cd ..

after_build:
  - move dedop-studio\dist win64
  - ps: cp $CONDA_INSTALLER_FILE win64

artifacts:
  - path: 'win64\DeDop*.exe'
    name: dedop-conda-installer-exe
  - path: 'win64\dedop-studio*.exe'
    name: dedop-studio-installer-exe

deploy:
  - provider: FTP
    protocol: ftp
    host: ftp.brockmann-consult.de
    username: dedop
    password:
      secure: GL7E4cOZi9mzFvaDMAVOaQ==
    debug: true