version: '0.5.4.dev.{build}'

environment:
  global:
    PYTHON_LOC: "C:\\Miniconda35-x64"
    INSTALLER_VERSION: "0.5.4.dev"

install:
  - cmd: call %PYTHON_LOC%\Scripts\activate.bat
  - cmd: conda config --set always_yes yes --set changeps1 no
  - cmd: conda install -y constructor

build_script:
  - cmd: constructor installer

artifacts:
  - path: 'DeDop*.exe'
    name: installer

deploy:
  - provider: FTP
    protocol: ftp
    host: ftp.brockmann-consult.de
    username: dedop
    password:
      secure: GL7E4cOZi9mzFvaDMAVOaQ==
    artifact: installer
    folder: win64
    debug: true