version: '1.0.1.dev.1.{build}'

environment:
  global:
    PYTHON_LOC: "C:\\Miniconda35-x64"
    FRONTEND_VERSION: "1.0.1-dev.1"
  nodejs_version: "6.9.0"
  apiUrl : "https://ci.appveyor.com/api"

# commented out for now because it creates problem when cloning the dedop-studio on the next build (dedop-studio directory
# already exists)
#cache:
#  - dedop-studio\node_modules -> package.json

install:
  - cmd: call %PYTHON_LOC%\Scripts\activate.bat
  - cmd: conda config --set always_yes yes --set changeps1 no
  - cmd: conda install -y constructor
  # now the frontend build
  - cmd: git clone https://github.com/DeDop/dedop-studio.gits
  - cmd: git checkout -b graphic_card_issue
  - cmd: cd dedop-studio
  - ps: $apiUrl
  - ps: Install-Product node $env:nodejs_version
  - cmd: npm install -g npm
  - cmd: npm install
  - cd ..

build_script:
  - cmd: constructor installer
  - ps: $CONDA_INSTALLER_FILE="DeDop*.exe"
  # bundled installer not yet used
  #- ps: cp $CONDA_INSTALLER_FILE dedop-studio\app
  - cmd: cd dedop-studio
  - cmd: npm run dist
  - ps: ls $APPVEYOR_BUILD_FOLDER
  - ps: echo $APPVEYOR_BUILD_FOLDER
  - ps: cd ..

after_build:
  - move dedop-studio\dist win64
  - ps: cp $CONDA_INSTALLER_FILE win64

artifacts:
  - path: 'win64\DeDop*.exe'
    name: dedop-conda-installer-exe
  - path: 'win64\dedop-studio*.exe'
    name: dedop-studio-installer-exe

deploy:
  - provider: FTP
    protocol: ftp
    host: ftp.brockmann-consult.de
    username: dedop
    password:
      secure: GL7E4cOZi9mzFvaDMAVOaQ==
    debug: true