version: '1.4.0.dev1.{build}'

environment:
  global:
    PYTHON_LOC: "C:\\Miniconda36-x64"
  nodejs_version: "6.9.0"
  apiUrl : "https://ci.appveyor.com/api"

# commented out for now because it creates problem when cloning the dedop-studio on the next build (dedop-studio directory
# already exists)
#cache:
#  - dedop-studio\node_modules -> package.json

install:
  - cmd: call %PYTHON_LOC%\Scripts\activate.bat
  - cmd: conda config --set always_yes yes --set changeps1 no
  - cmd: conda install -y constructor
  # now the frontend build
  - cmd: git clone https://github.com/DeDop/dedop-studio.git
  - cmd: cd dedop-studio
  - ps: $apiUrl
  - ps: Install-Product node $env:nodejs_version
  - cmd: npm install -g npm
  - cmd: npm install
  - cd ..

build_script:
  - cmd: constructor installer
  - cmd: cd dedop-studio
  - cmd: npm run clean
  - cmd: npm run compile
  - cmd: npm run publish